### PR TITLE
Replace alert notifications

### PR DESCRIPTION
**Pull request by shahidajmeri786**
Replaced alert with notifications  in apps such as:
Subscribe form
Media attachment detail changes saved
Term detail changes saved
Post detail changes saved
Update app

### CODE REVIEW

**Comment by fastlinemedia** [comment]
Thanks @shahidajmeri786 this looks great! I did noticed it looks like some of the subscribe form logic is in this branch. Maybe you branched off the wrong branch? Can we get that removed since we're not ready to merge it yet?

**Comment by shahidajmeri786** [comment]
Hi Justin,
I merged the new-subscribe-form branch to replace the alert branch and i have off of it because i need changes of subscriber form for replacing alerts.

**Comment by fastlinemedia** [comment]
Thanks @shahidajmeri786, that works for me. 

Can we make these messages dismissible? I think that might help with it being in the publish bar. Also, if I cancel after publishing, the message is still there. I think once you start making changes, it should go away. 

https://share.getcloudapp.com/8LuJneJg

**Comment by shahidajmeri786** [comment]
Hi Justin,

I added a close icon and it's working it will dismiss the notification but the blank footer is still there. and I toggle the class-based on click state change.  so the state is inside the message component. now I am confused about if with message dismiss should I need to hide footer? then how can i pass the message close state to an app?

image

**Comment by fastlinemedia** [comment]
@shahidajmeri786 can you add an event to the message component? Something like this...

```
<Layout.Message
	status={responseMessage.status}
	icon={responseMessage.icon}
	onDismiss={() => {
		setResponseMessage( ... )
	}}
>
	{responseMessage.message}
</Layout.Message>
```

**Comment by shahidajmeri786** [comment]
Hi Justin,
Event is not working because the close functionality is our own. we have span tag with "X" sign and on-click event we are set to display none to the message body. i pushed code so you get the idea

**Comment by fastlinemedia** [comment]
@shahidajmeri786 are you sure it was pushed? I'm not seeing any new commits on this branch.

**Comment by shahidajmeri786** [comment]
Hello Justin, 
I was tried with the event but due to we have different for closing the message I reverted back with the code without event.

**Comment by fastlinemedia** [comment]
@shahidajmeri786 let's not worry about the footer notifications for now then. We'll be doing an actual notification system after this next release. So, it's probably not worth spending any more time on it. Can you change that back and we'll get this merged?

**Comment by shahidajmeri786** [comment]
> @shahidajmeri786 let's not worry about the footer notifications for now then. We'll be doing an actual notification system after this next release. So, it's probably not worth spending any more time on it. Can you change that back and we'll get this merged?

@fastlinemedia : I think we should not need to merge this now. I will create a new branch for the next release notification task is that ok?

**Comment by fastlinemedia** [comment]
@shahidajmeri786 sounds good, thanks.

**Comment by fastlinemedia** [comment]
Closing this in favor of #188.

**Pull request closed without merging**
