### PR TITLE
Added post export action

### PR DESCRIPTION
**Pull request by shahidajmeri786**
Created single post export action.
For quick view refer here: https://www.loom.com/share/0b6d1fa88a194d27a3afe458b4729613

### CODE REVIEW

**Comment by fastlinemedia** [comment]
Thanks, @shahidajmeri786! This works great. 

There are a couple things I noticed on the code side...

Can you make the XML a template/view instead of including it in the class. It's verbose and makes the class harder to follow.

For reference, you can put templates in the `backend/templates` directory. For an example of including a template, see `backend/src/Hooks/Actions/OnEditUserProfile.php`. 

The other thing I'm seeing is where the temporary file is stored. Can we store that in wp-content instead of the plugin directory? 

Thanks!

**Comment by fastlinemedia** [comment]
@brentjett are you fine with where the Export button is located or do you have feedback there?

https://share.getcloudapp.com/RBud4KoR

**Comment by brentjett** [comment]
I’m good with it. Maybe make trash the last action.

**Comment by shahidajmeri786** [comment]
Hello Justin,
I tried making template but unfortunately, it is not working and the execution stops at the include function at view.php. I troubleshoot and found that the directory structure is not properly working.
do you have any idea?

**Comment by fastlinemedia** [comment]
@shahidajmeri786 can you push what you have so I can test it out and see what isn't working?

**Comment by shahidajmeri786** [comment]
Hy Justin,
I pushed the code. you can check.

**Comment by fastlinemedia** [comment]
Thanks, @shahidajmeri786. `$this->view->render` will echo the string. Can you try `$this->view->render_to_string` instead?

**Comment by shahidajmeri786** [comment]
Thanks, @fastlinemedia . The issue was in the XML template creation. I resolved and now working fine.

**Comment by fastlinemedia** [comment]
Thanks, @shahidajmeri786! 

Can you look at these last two items? 

> The other thing I'm seeing is where the temporary file is stored. Can we store that in wp-content instead of the plugin directory?

>I’m good with it. Maybe make trash the last action.

**Comment by fastlinemedia** [comment]
Also, mind making sure all PHP and JS lint tests pass when you're done?  Thanks!

**Comment by shahidajmeri786** [comment]
Hi @fastlinemedia ,

Resolved :

- Now temporary files stores into the wp-content directory
- Made trash as the last action
- Resolved phpcs errors and warning for postController.php and fixed npm errors using npm run fix

**Comment by fastlinemedia** [comment]
Thanks @shahidajmeri786, I just tested and it looks like the export file is empty. Can you check that out? Also, it looks like the `delete_export` method is still trying to delete the export file from the Assistant plugin folder.

**Comment by shahidajmeri786** [comment]
> Thanks @shahidajmeri786, I just tested and it looks like the export file is empty. Can you check that out? Also, it looks like the `delete_export` method is still trying to delete the export file from the Assistant plugin folder.

Hi @fastlinemedia ,
Thanks for testing.  I tested twice but for my case, the export file is not empty and working properly. for reference see here: https://www.screencast.com/t/7GfPGoSKw4

The delete file looking for plugin folder is resolved.

**Comment by fastlinemedia** [comment]
@shahidajmeri786 I'm seeing this error when trying to export a post...

> PHP Warning:  file_get_contents(/Server/wordpress/wp-content/test_22101.xml): failed to open stream: No such file or directory in //Server/wordpress/wp-content/plugins/assistant-git/backend/src/Controllers/PostsController.php on line 472

It looks like the issue is in the logic where you're checking if the file exists. If it does, you are unlinking it and then calling `file_get_contents` below that. Since you just unlinked it, the file doesn't exist anymore. 

```
$file_url = WP_CONTENT_URL .'/'. $post->post_title . '_' . $post->ID . '.xml';
$file = WP_CONTENT_DIR .'/'. $post->post_title . '_' . $post->ID . '.xml';

if ( file_exists( $file ) ) {
	unlink( $file );
	$file = WP_CONTENT_DIR .'/'. $post->post_title . '_' . $post->ID . '.xml';
}

$current = file_get_contents( $file );
```
I also notice that you're redefining `$file` with the same path, is that necessary? Do you need to append the XML if the file exists or can you just create a new file each time? 

Finally, I think you should use `sanitize_file_name` on the filename since the post title might not be safe. 

Let me know how it goes.

**Comment by shahidajmeri786** [comment]
> @shahidajmeri786 I'm seeing this error when trying to export a post...
> 
> > PHP Warning:  file_get_contents(/Server/wordpress/wp-content/test_22101.xml): failed to open stream: No such file or directory in //Server/wordpress/wp-content/plugins/assistant-git/backend/src/Controllers/PostsController.php on line 472
> 
> It looks like the issue is in the logic where you're checking if the file exists. If it does, you are unlinking it and then calling `file_get_contents` below that. Since you just unlinked it, the file doesn't exist anymore.
> 
> ```
> $file_url = WP_CONTENT_URL .'/'. $post->post_title . '_' . $post->ID . '.xml';
> $file = WP_CONTENT_DIR .'/'. $post->post_title . '_' . $post->ID . '.xml';
> 
> if ( file_exists( $file ) ) {
> 	unlink( $file );
> 	$file = WP_CONTENT_DIR .'/'. $post->post_title . '_' . $post->ID . '.xml';
> }
> 
> $current = file_get_contents( $file );
> ```
> 
> I also notice that you're redefining `$file` with the same path, is that necessary? Do you need to append the XML if the file exists or can you just create a new file each time?
> 
> Finally, I think you should use `sanitize_file_name` on the filename since the post title might not be safe.
> 
> Let me know how it goes.

Thanks, Justin for a test. I realized that that code was not needed anymore. I also sanitize filename.

**Comment by fastlinemedia** [comment]
Thanks @shahidajmeri786! I figured out the issue on my end with the empty file. The path in the base View class was using backslashes instead of forward slashes. Can you double check that this still works on your system?

**Comment by fastlinemedia** [comment]
FYI, I merged master so be sure to `npm install`. Lots of changes there :)

**Comment by fastlinemedia** [comment]
@shahidajmeri786 I just tested importing a post exported an Assistant on another site and it's not working. The import completes but the post isn't showing up. Can you check that out?

**Comment by fastlinemedia** [comment]
Posting our conversation in Slack for reference here...

Hey Shahid, I just tested the export from one site to another again.

It is actually working, however, there are two issues I’m seeing:

1. The post title is coming through blank.
2. Beaver Builder data is getting corrupted.

For the BB data, you can export a page built with BB and then import it onto another site. It should show the BB layout.

I think one issue might be that core wraps a lot of export data in a function called `wxr_cdata`.

Can you look at the core export code for that? We also have a fork in BB under `classes-fl-export.php` and `includes/export.php`.

**Comment by shahidajmeri786** [comment]
> 2\. Beaver Builder

Hi @fastlinemedia ,

I tested with BB page. exported from one site and imported in another site where the BB is installed.
You are right that BB data is corrupted but I checked the existing BB page and imported BB page and found that both have the same content. then I tried another thing, I created a new page in existing BB page site and pasted existing BB page code into a new page and the result is same. the page has corrupted BB layout.

The export app just uses the content of the page/post. if BB code working on a new page by pasting its layout code then the export app can also work same.

for quick view check here : https://www.screencast.com/t/H1W9FkG27TX

let me know your thougts

**Comment by fastlinemedia** [comment]
Hey @shahidajmeri786 BB saves its layout data to post meta, I'm not sure what I'm seeing in that video. 

You can try this without Assistant. Create a BB page, apply a BB template, publish in BB and then do the export import process. Assistant _needs_ to work like that. 

Usually this doesn't work because serialized meta data is being corrupted. So I'd suggest looking into what I mentioned in my last comment. I think we might need that `wxr_cdata` function. At least take a look at what core is doing there with meta. 

Did you also look at the post title coming in empty?

**Comment by shahidajmeri786** [comment]
> Hey @shahidajmeri786 BB saves its layout data to post meta, I'm not sure what I'm seeing in that video.
> 
> You can try this without Assistant. Create a BB page, apply a BB template, publish in BB and then do the export import process. Assistant _needs_ to work like that.
> 
> Usually this doesn't work because serialized meta data is being corrupted. So I'd suggest looking into what I mentioned in my last comment. I think we might need that `wxr_cdata` function. At least take a look at what core is doing there with meta.
> 
> Did you also look at the post title coming in empty?

Hi @fastlinemedia ,

Thanks for testing. I fixed the issue now BB layout page is also exported well without corruption of the metadata. I tested and works well with BB layout page. I also tested that post title also imported correctly. I pushed the code. can you please test again?

thanks!

**Comment by fastlinemedia** [comment]
Resolves #214

**Pull request merged**
