### PR TITLE
get_edit_user_link needs 1 params

### PR DESCRIPTION
**Pull request by szepeviktor**
https://developer.wordpress.org/reference/functions/get_edit_user_link/

### CODE REVIEW

**Comment by brentjett** [comment]
Hi Viktor,
I appreciate the interest in the project but we're not quite ready to accept outside PRs just yet. This product is currently part of a competition that requires that it only have 3 participants, which we have. In the future we will be open to outside PRs. Thanks again!

**Comment by szepeviktor** [comment]
Thanks.
Can I be the third one? https://github.com/beaverbuilder/assistant/graphs/contributors

**Comment by brentjett** [comment]
I'm afraid we do have a 3rd from our team. He is not a code contributor but he is a participant in its creation. Sorry!

**Comment by szepeviktor** [comment]
Please consider using PHPStan for the development, it need only 2 stubs

phpstan.neon

```yaml
parameters:
    # Do raise level here!
    level: 2
    paths:
        - %currentWorkingDirectory%/classes/
    autoload_files:
        - %currentWorkingDirectory%/vendor/giacocorsiglia/wordpress-stubs/wordpress-stubs.php
        - %currentWorkingDirectory%/classes/class-fl-assistant-plugin-loader.php
        - %currentWorkingDirectory%/tests/bb-theme-stubs.php
    autoload_directories:
        - %currentWorkingDirectory%/classes/
    ignoreErrors:
        - '#^Function add_query_arg invoked with [23] parameters, 0 required\.$#'
        - '#^Function current_user_can invoked with 2 parameters, 1 required\.$#'
```

**Comment by brentjett** [comment]
thanks for the suggestion!

**Comment by szepeviktor** [comment]
@brentjett I've finished with the analysis.

1. Please consider moving `FL_Assistant_Plugin_Loader::init();` to the main file
1. Please consider moving `define()`-s to the main file

See Yoast SEO for plugin structure.

And if you'll have time to receive fixes for bugs discovered by PHPStan please ping me.

**Comment by fastlinemedia** [comment]
Thanks @szepeviktor! May I ask why this is necessary? We do it this way in our plugins to ensure things are only setup once.

**Comment by szepeviktor** [comment]
Calling init() pollutes the class file, a clean class file has no side effects.
define() defines *global* constants not fitting in a class. Please see https://github.com/Yoast/wordpress-seo/blob/trunk/wp-seo.php#L43-L48

And static analysis fails if you do the two thing above.

off: You're welcome to comment on my experiment on running WordPress core 10% faster: https://github.com/szepeviktor/wordpress-autoloaded

**Comment by brentjett** [comment]
That might be the case if these were classes that were meant to be instantiated, but these are purely for static functions. There's no issue with polluting the file here. Many developers use classes in this way.

**Pull request closed without merging**
