### PR TITLE
Updates App: List view tabs

### LINKED ISSUE #179: Updates App: Hook up list view tabs
Hook up the list view tabs for switching between update types.

### PR DESCRIPTION
**Pull request by fastlinemedia**
Resolves #179

### CODE REVIEW

**Comment by fastlinemedia** [comment]
@shahidajmeri786 this is looking great, thanks!

Just two things I noticed...

1) Clicking on a list item doesn't go to the detail view. 

2) Do you think we should split out the `UpdateButton` component from the `getItemProps` function so it only has to be defined once?

**Comment by shahidajmeri786** [comment]
@fastlinemedia  :
**Clicking on a list item doesn't go to the detail view:**
I checked but I do not find "to:" into list items and also we do not have any component file/folder into ui/pages for updates.

**Do you think we should split out the UpdateButton component from the getItemProps function so it only has to be defined once?**
- I made it common within same file is ok? or I need to define a separate component. I do not get the best place to define component inside the list

**Comment by fastlinemedia** [comment]
@shahidajmeri786 

> **Clicking on a list item doesn't go to the detail view:**
> I checked but I do not find "to:" into list items and also we do not have any component file/folder into ui/pages for updates.

Sorry, the page component is `themes-plugins`. If you checkout `new-ui`, you'll see you can click to the detail view in that branch.

> **Do you think we should split out the UpdateButton component from the getItemProps function so it only has to be defined once?**
> * I made it common within same file is ok? or I need to define a separate component. I do not get the best place to define component inside the list

That looks good. I'm wondering though, why not use `List.Updates` instead of `List.WordPress` as `List.Updates` already defines the update button in a single place? We still have two copies of that component in the codebase doing it this way.

**Comment by fastlinemedia** [comment]
@shahidajmeri786 one last thing, can we rework the list buttons into a filter? Brent already has the components setup in `new-ui` if you merge that in...

https://share.getcloudapp.com/DOuvp0Bd

**Comment by shahidajmeri786** [comment]
> @shahidajmeri786
> 
> > **Clicking on a list item doesn't go to the detail view:**
> > I checked but I do not find "to:" into list items and also we do not have any component file/folder into ui/pages for updates.
> 
> Sorry, the page component is `themes-plugins`. If you checkout `new-ui`, you'll see you can click to the detail view in that branch.
> 
> > **Do you think we should split out the UpdateButton component from the getItemProps function so it only has to be defined once?**
> > 
> > * I made it common within same file is ok? or I need to define a separate component. I do not get the best place to define component inside the list
> 
> That looks good. I'm wondering though, why not use `List.Updates` instead of `List.WordPress` as `List.Updates` already defines the update button in a single place? We still have two copies of that component in the codebase doing it this way.

- Now List.Updates is used.

**Comment by shahidajmeri786** [comment]
> @shahidajmeri786 one last thing, can we rework the list buttons into a filter? Brent already has the components setup in `new-ui` if you merge that in...
> 
> https://share.getcloudapp.com/DOuvp0Bd

- Removed tabs and reworked with new filters.

**Comment by shahidajmeri786** [comment]
@brentjett : I added one condition in List.scroller as i found issue when there are no items it show '0' below the empty message:
image
I added the below condition:
image
and now it's working.

**Pull request merged**
